### ISSUE TITLE
Windows: use USERPROFILE instead of HOME variable

### ISSUE THREAD

**Issue by johnd0e** [efugier/smartcat#25]

**Comment by efugier** [comment]
Hey, I never worked on windows machines so my knowledge about the issue is a bit limited.

Can you tell me what you think would be the ideal behavior:
1. Check `$HOME` then `$USERPROFILE` if there's no `$HOME`
2. Check `$USERPROFILE` only on windows and `$HOME` on everything else

That said, you currently can have the config live anywhere as per the README:
https://github.com/efugier/smartcat/blob/546995626bb086780350486f90dea9388af6d94c/README.md?plain=1#L216-L217

**Comment by johnd0e** [comment]
I think 2 is better.

**Comment by johnd0e** [comment]
Worth to mention that there are other related variables on Linix/Macos too: https://github.com/sigoden/aichat/pull/889

**Comment by efugier** [comment]
Thanks for pointing it out but one default by OS will be where I draw the line.

If people want to have a custom directory there still is the `SMARTCAT_CONFIG_PATH` env variable that can be set to anything they want!
