### ISSUE TITLE
Possibility to set api_key using env variable and command line option

### ISSUE THREAD

**Issue by johnd0e** [efugier/smartcat#26]

**Comment by efugier** [comment]
Hey, thanks for asking!

You had a cli option although a bit limited: instead of `api_key`, you can use `api_key_command` as demonstrated here https://github.com/efugier/smartcat/blob/91943a6a7b0583cd645dd6739aa50fabb2890821/README.md?plain=1#L243

The issue was that it wasn't running the command in a shell so the syntax to read environment variable didn't work.

More context here: https://github.com/rust-lang/rust/issues/95400#issuecomment-1080971765

In the end I just released [1.5.0](https://github.com/efugier/smartcat/releases/tag/1.5.0) and made switch from just running the command to actually using the shell. The potential issue is it requires an installed and working `sh`, which isn't always the case on windows machines.

But now you're able to use
```
api_key_command = "echo $MY_API_KEY"
```

which should solve your issue :slightly_smiling_face:

**Comment by johnd0e** [comment]
This doesn't work:
```
api_key_command = "echo %GROQ_API_KEY%"
```

But this works:
```
api_key_command = "cmd /c echo %GROQ_API_KEY%"
```

Perhaps you could adapt shell to use `cmd.exe /c "command"` on Windows.
Full path to the shell is in the COMSPEC variable:
```env
ComSpec=C:\Windows\system32\cmd.exe
```

**Comment by efugier** [comment]
> This doesn't work:
> `api_key_command = "echo %GROQ_API_KEY%"`

@johnd0e, this is expected, as it's `sh` that is used. If available on your machine (and it is because `cmd something works`, the correct syntax is `echo $GROQ_API_KEY`.

That said, now that I started writing different code for windows and unix I might as well go all the way, try version [1.7.0](https://github.com/efugier/smartcat/releases/tag/1.7.0)

Let me know if it works are intended this time!

**Comment by johnd0e** [comment]
> correct syntax is echo $GROQ_API_KEY

You are right, that works on my system

**Comment by efugier** [comment]
Great! Can you tell me if the windows syntax `api_key_command = "echo %GROQ_API_KEY%"` now works on your system?

It should after `1.7.0` but I want to check because of the backslash (among other things) for `\c`.

**Comment by johnd0e** [comment]
1.7.0 is ok, thanks
